name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v3  # Node.js 20対応のバージョンを使用
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Node.js 20対応のバージョンを使用
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    - name: Run tests
      run: |
        pytest
